eventastic/urls.py
from django.urls import path
from eventastic import views

app_name = 'eventastic'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name="login"),
    path('contact-us/', views.contact_us, name="contact_us"),
    path('login/account/', views.account, name='account'),
    path('login/account/edit/', views.edit_account, name='edit_account'),
    path('login/account/delete/', views.delete_account, name='delete_account'),
    path('logout/', views.user_logout, name='logout'),
    path('categories/', views.categories, name='categories'),
    path('categories/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('create-category/', views.create_category, name='create_category'),
    path('create-event/', views.create_event, name='create_event'),
    path('categories/<slug:category_name_slug>/<slug:event_name_slug>/', views.show_event, name='show_event'),
    path('find-users/', views.find_users, name="find_users"),
    path('find-users/<slug:user_slug>/', views.show_user_events, name="show_user_events"),
    path('interest/', views.interest, name='interest'),
]

eventastic_project/urls.py
from django.contrib import admin
from django.urls import path, include
from eventastic import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('eventastic/', include('eventastic.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventastic/forms.py
from django import forms
from django.contrib.auth.models import User

from eventastic.models import UserProfile, Category, Event, Comment

# Forms used in the Eventastic Project
# All the form inputs are styled with the Bootstrap form control class as seen in the widgets

# Form to register a new User (this form takes in data associated with the User Table)
class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password',)

        help_texts = {
            'username': None
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    # Clean this data and raise an error if the two password fields do not match
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm password fields do not match"
            )

        elif len(password) < 8:
            raise forms.ValidationError(
                "password is too short"
            )

        elif (password.isdecimal()):
            raise forms.ValidationError(
                "password cannot only contain numbers"
            )


# Form to register a new User (this form takes in data associated with the UserProfile Table)
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('DOB', 'profilePicture')

        labels = {
            'DOB': 'Date of Birth',
            'profilePicture': 'Profile Picture'
        }

        widgets = {
            'DOB': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD', 'type': 'date'}),
            'profilePicture': forms.FileInput(attrs={'class': 'form-control'}),
        }

# Form to create a new category in the Eventastic web app
class CategoryForm(forms.ModelForm):
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', 'description', 'picture')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'picture': forms.FileInput(attrs={'class': 'form-control'}),
        }


# Form to create a new event in the Eventastic web app
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('category', 'name', 'description', 'startDate', 'startTime', 'address', 'postcode', 'picture')

        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'startDate': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'YYYY-MM-DD'}),
            'startTime': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time', 'placeholder': 'hh-mm'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'postcode': forms.TextInput(attrs={'class': 'form-control'}),
            'picture': forms.FileInput(attrs={'class': 'form-control'}),
        }


# Form to update details associated with the User Table
class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }


# Form to update details associated with the UserProfile Table
class EditProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('DOB', 'profilePicture',)

        widgets = {
            'DOB': forms.DateInput(attrs={'class': 'form-control'}),
            'profilePicture': forms.FileInput(attrs={'class': 'form-control'}),
        }


# Form to provide confirmation before deleting an account
class DeleteUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('password',)

        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


# Form to add a new comment to an existing event
class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

eventastic/views.py
from django.shortcuts import render, redirect
from eventastic.forms import UserForm, UserProfileForm, CategoryForm, EventForm, EditUserForm, EditProfileForm, DeleteUserForm, AddCommentForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from eventastic.models import Category, Event, UserProfile, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.views import View
from geopy import Nominatim
from django.core.files.images import ImageFile

"""
This view renders the home page onscreen
"""
def index(request):
    # Define empty context dictionary
    context_dict = {}

    # Get the 9 events with the most users interested and store them in the context dictionary
    top_events = Event.objects.order_by('-numberInterested')[:9]
    context_dict['top_events'] = top_events

    return render(request, 'eventastic/index.html', context=context_dict)

"""
This view renders the register page and form onscreen
"""
def register(request):
    # Define empty context dictionary
    context_dict = {}

    # If the method is POST (form has been submitted) the form will be processed
    if request.method == 'POST':
        # Get the information from the forms
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # if the form information is valid then the information will be saved
        if user_form.is_valid() and profile_form.is_valid():
            # Save the User form information in the database
            user = user_form.save()

            # Hash the saved password and resave it
            user.set_password(user.password)
            user.save()

            # Save the User Profile form information in the database
            profile = profile_form.save(commit=False)
            profile.user = user

            # If the user attaches a picture then save that picture as their profile picture
            if 'profilePicture' in request.FILES:
                profile.profilePicture = request.FILES['profilePicture']
            # Else use the default profile picture
            else:
                profile.profilePicture = ImageFile(open("static/images/default_profile_picture.jpg", 'rb'))

            # Finalise the changes to the user profile
            profile.save()

            # Login the newly registered user
            new_user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            login(request, new_user)

            # Redirect the user to the home page
            return redirect(reverse('eventastic:index'))

        # If the form information is not valid then print error
        else:
            messages.error(request, "Form is invalid")

    # If the form has not been submitted display the form onscreen
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Add the forms to the context dictionary
    context_dict['user_form'] = user_form
    context_dict['profile_form'] = profile_form

    # Render the view onscreen using the given context
    return render(request, 'eventastic/register.html', context = context_dict)

"""
This view renders the user login page and form onscreen
"""
def user_login(request):

    # Define the context dictionary with an empty error message
    context_dict = {'error_message': None}

    # If the method is POST (form has been submitted) the form will be processed
    if request.method == 'POST':
        # Get the username and password values from the POST request
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Attempt to authenticate the user with the provided details
        user = authenticate(username=username, password=password)

        # If a user with the given username and password exists
        if user:
            # Check that their account is still active
            # If it is then log the user in
            if user.is_active:
                login(request, user)

                # Redirect the user back to the home page
                return redirect(reverse('eventastic:index'))

            # If the account exists but is disabled, display an error message
            else:
                context_dict['error_message'] = "Account is disabled"

        # If an account with the given details does not exist, display an error message
        else:
            context_dict['error_message'] = "Username or Password is incorrect"

    # If the form has not been submitted, render the view onscreen
    return render(request, 'eventastic/login.html', context=context_dict)


"""
This view logs out a logged in user
"""
@login_required
def user_logout(request):
    # Log the user out
    logout(request)

    # Redirect the user back to the home page
    return redirect(reverse('eventastic:index'))

"""
This view renders a page ccontaining information about a category onscreen
"""
def show_category(request, category_name_slug):
    # Define empty context dictionary
    context_dict = {}

    try:
        # Get the category with the given category_name_slug
        category = Category.objects.get(slug=category_name_slug)

        # Get all the events that come under that category
        events = Event.objects.filter(category=category)

        # store the category and events in the context dictionary
        context_dict['events'] = events
        context_dict['category'] = category

    # If a category with the given category_name_slug does not exist
    # then display None in the 'category' and 'events' spaces in context dictionary
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['events'] = None

    # Finally, render the view onscreen using the given context
    return render(request, 'eventastic/show_category.html', context=context_dict)

"""
This view renders the create category page and form onscreen
"""
@login_required
def create_category(request):
    # Define empty context dictionary
    context_dict = {}

    # If the method is POST (form has been submitted) the form will be processed
    if request.method == 'POST':
        # Get the data from the form
        form = CategoryForm(request.POST)

        # If the form information is valid then save the information in the database
        if form.is_valid():
            form_data = form.save(commit=False)

            if 'picture' in request.FILES:
                form_data.picture = request.FILES['picture']
            else:
                form_data.picture = ImageFile(open("static/images/category_and_event_default.jpg", 'rb'))

            form_data.save()

            # Get the slug for the created category
            category_name_slug = form_data.slug
            # Redirect the user to the page for that category using the slug
            return redirect('eventastic:show_category', category_name_slug=category_name_slug)

        # If the form information is not valid display an error
        else:
            messages.error(request, "Form is invalid")

    # Define the form that needs to be displayed onscreen
    form = CategoryForm()

    # Add the form to the context dictionary
    context_dict['form'] = form

    # If the form has not been submitted then render the view onscreen
    return render(request, 'eventastic/create_category.html', context=context_dict)

"""
This view renders a page containing information about an event onscreen
"""
def show_event(request, category_name_slug, event_name_slug):
    # Define empty context dictionary
    context_dict = {}

    try:
        # Get the event with the given event_name_slug
        event = Event.objects.get(slug=event_name_slug)
        # Store the event in the context dictionary
        context_dict['event'] = event

    # If an event with the given event_name_slug does not exist
    # then display None in the 'event' space in context dictionary
    except Event.DoesNotExist:
        context_dict['event'] = None

    try:
        # Get the currently logged in user
        user_profile = UserProfile.objects.get(user=request.user.id)
        # Check if that user is in the Many to Many field in the current event
        is_interested = event.usersInterested.filter(user=user_profile).exists()
        # Store a boolean value in the context dictionary indicating if the user is in the Many to Many field
        context_dict['is_interested'] = is_interested
    except:
        # If the user is not logged in set is_interested to False
        context_dict['is_interested'] = False

    # Create a locator using the geopy external library
    locator = Nominatim(user_agent="eventastic")

    try:
        # Get the location data about the postcode of the current event
        location = locator.geocode(event.postcode)

        # Store the latitude and longitude of the postcode to be used in the MapBox API
        context_dict['latitude'] = location.latitude
        context_dict['longitude'] = location.longitude

    except:
        # If the postcode is not valid then store None for the latitude and longitude
        context_dict['latitude'] = None
        context_dict['longitude'] = None

    # Get all the comments for the current event and store them in the context dictionary
    comments = Comment.objects.filter(eventName=event)
    context_dict['comments'] = comments

    # If the add comment form is submitted
    if request.method == 'POST':
        # If the user is not logged in redirect them to the login page
        if not request.user.is_authenticated:
            return redirect('eventastic:login')

        # Get the data from the form
        form = AddCommentForm(request.POST)

        # If the form is valid
        if form.is_valid():

templates/eventastic/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load eventastic_template_tags %}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' rel='stylesheet'/>

    <title>
        Eventastic -
        {% block title_block %}
            Default
        {% endblock %}
    </title>
</head>

<body>
<div class="wrapper">
<!-- Page header -->
<header>
    <a href="{% url 'eventastic:index' %}">
      <img class="d-inline px-2 py-2 header-image" src="{% static 'images/logo.png' %}"/>
    </a>

    {% if user.is_authenticated %}
        <span class="px-2 py-2 header-container">
          <a class="mx-2 sidebar-list" href="{% url 'eventastic:account' %}">{{ request.user }}</a>
          {% get_user_profile_pic request.user.id %}
        </span>
    {% endif %}
</header>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light border-top border-bottom border-1 border-dark set-secondary-background">
    <div class="container-fluid">
        <a class="navbar-brand d-lg-none">Navigation</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:index' %}">Home</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:categories' %}">Categories</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:create_category' %}">Create Category</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:create_event' %}">Create Event</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:find_users' %}">Find Users</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link" href="{% url 'eventastic:contact_us' %}">Contact Us</a>
                </li>
            </ul>
        </div>

        <!-- Store the urls for the register and log in page -->
        {% url 'eventastic:register' as register_url %}
        {% url 'eventastic:login' as login_url %}

        <span>
          <!-- If the user is logged in display the logout button in the nav bar-->
          {% if user.is_authenticated %}
              <button type="button" onclick="document.location='{% url 'eventastic:logout' %}'" class="btn button-custom px-3 border-1 border-dark m-1">Logout</button>
          <!-- If the user is not logged in and is not on the reguster or login page display the login and reguster buttons in the nav bar -->
          <!-- We don't want to display these buttons on the login and register page as they are already there -->
          {% elif request.path != register_url and request.path != login_url %}
              <button type="button" onclick="document.location='{{ login_url }}'" class="btn button-custom px-3 border-1 border-dark m-1">Login</button>
              <span>or</span>
              <button type="button" onclick="document.location='{{ register_url }}'" class="btn button-custom px-3 border-1 border-dark m-1">Register</button>
          {% endif %}
        </span>

          <!-- Toggler to display the nav bar if the screen gets too small -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    </div>
</nav>

<!-- Side Bar -->
<div class="border-top border-bottom border-1 border-dark ms-2 sidebar">
        {% if user.is_authenticated %}
            <h5 class="p-2">Hello, {{ request.user }}</h5>
        {% endif %}

        {% get_recently_published_events as recently_published_events %}
        {% get_top_categories as top_categories %}
        {% get_top_organisers as top_organisers %}

        <div class="accordion accordion-flush" id="accordionFlushExample">
            <!-- Display the most recently published events -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      Recently Published Events
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <ol>
                            {% for event in recently_published_events %}
                                <li>
                                    <a class="sidebar-list" href="{% url 'eventastic:show_event' event.category.slug event.slug %}">{{ event.name }}</a>
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
            <!-- Display the top categories -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                        Top Categories
                    </button>
                </h2>
                <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <ol>
                            {% for category in top_categories %}
                                <li>
                                    <a class="sidebar-list" href="{% url 'eventastic:show_category' category.slug %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
            <!-- Display the top organisers -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                        Top Organisers
                    </button>
                </h2>
                <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <ol>
                            {% for user in top_organisers %}
                                <li>
                                    <a class="sidebar-list" href="{% url 'eventastic:show_user_events' user.user.id %}">{{ user.user }}</a>
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main page content -->
    <div class="body-block">
        {% block body_block %}
        {% endblock %}
    </div>
</div>

<!-- Footer -->
<footer id="footer" class="py-3 border-top set-secondary-background">
  <a class="list m-5" href="https://youtube.com">
    <!-- Youtube Image -->
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
    <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
  </svg>
  </a>

  <a class="list m-5" href="https://twitter.com">
    <!-- Twitter image -->
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
    </svg>
  </a>

  <a class="list m-5" href="https://instagram.com">
    <!-- Instagram image -->
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
    </svg>
  </a>

  <p class="text-dark mt-3">© 2021 Copyright Eventastic</p>
</footer>

<!-- Import Bootstrap JS and our custom JS for the map and the interest button -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/eventastic_ajax.js' %}" crossorigin="anonymous"></script>

</body>
</html>

templates/eventastic/create_event.html
{% extends 'eventastic/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Create Event
{% endblock %}

<!-- Create an event form-->
{% block body_block %}
    <h1>Create an Event</h1>
    <div class="mb-2">
        <form id="category_form" method="post" action="{% url 'eventastic:create_event' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <input class="btn button-custom px-3 border-1 border-dark" type="submit" name="submit" value="Create Event"/>
        </form>
    </div>
{% endblock %}